// Code generated by hertz generator.

package main

import (
	"context"
	"os"
	"time"

	"github.com/cloudwego/biz-demo/gomall/app/frontend/biz/router"
	"github.com/cloudwego/biz-demo/gomall/app/frontend/conf"
	"github.com/cloudwego/biz-demo/gomall/app/frontend/middleware"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/middlewares/server/recovery"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/hertz-contrib/cors"
	"github.com/hertz-contrib/gzip"
	"github.com/hertz-contrib/logger/accesslog"
	hertzlogrus "github.com/hertz-contrib/logger/logrus"
	"github.com/hertz-contrib/pprof"
	 "github.com/hertz-contrib/monitor-prometheus"
	"go.uber.org/zap/zapcore"
	"gopkg.in/natefinch/lumberjack.v2"
       
	"github.com/cloudwego/biz-demo/gomall/app/frontend/infra/rpc"
	frontendutils "github.com/cloudwego/biz-demo/gomall/app/frontend/utils"
	"github.com/cloudwego/biz-demo/gomall/common/mtl"
	"github.com/hertz-contrib/sessions"
	"github.com/hertz-contrib/sessions/redis"
	"github.com/joho/godotenv"
    hertztracing "github.com/hertz-contrib/obs-opentelemetry/tracing"
	hertzobslogrus "github.com/hertz-contrib/obs-opentelemetry/logging/logrus"
)
var (
	ServiceName =frontendutils.ServiceName
	MetricsPort = conf.GetConf().Hertz.MetricsPort
	RegistryAddr = conf.GetConf().Hertz.RegistryAddr
)

func main() {
	// init dal
	// dal.Init()
	_ = godotenv.Load()
	p :=mtl.InitTracing(ServiceName)
	defer p.Shutdown(context.Background())

	consul,registryInfo := mtl.InitMetric(ServiceName,MetricsPort,RegistryAddr)
	defer consul.Deregister(registryInfo)
	
	rpc.Init()
	address := conf.GetConf().Hertz.Address

	tracer, cfg := hertztracing.NewServerTracer()

	h := server.New(server.WithHostPorts(address),
	server.WithTracer(prometheus.NewServerTracer("","",prometheus.WithDisableServer(true),prometheus.WithRegistry(mtl.Registry),
	)),tracer,
)
    h.Use(hertztracing.ServerMiddleware(cfg))

	registerMiddleware(h)

	// add a ping route to test
	h.GET("/ping", func(c context.Context, ctx *app.RequestContext) {
		ctx.JSON(consts.StatusOK, utils.H{"ping": "pong"})
	})

	router.GeneratedRegister(h)
	h.LoadHTMLGlob("template/*")
	h.Static("/static","./")
    
	h.GET("/sign-in", func(c context.Context, ctx *app.RequestContext) {
		data:=utils.H{
			"Title":"Sign In",
			"Next": ctx.Query("next"),
		}
		ctx.HTML(consts.StatusOK,"sign-in",data)
	})
	h.GET("/about",func(c context.Context, ctx *app.RequestContext) {
		hlog.CtxInfof(c,"CloudweGo shop about page")
        ctx.HTML(consts.StatusOK, "about", utils.H{"Title": "About"})
    })
	h.GET("/sign-up", func(c context.Context, ctx *app.RequestContext) {
		ctx.HTML(consts.StatusOK,"sign-up",utils.H{"Title":"Sign In"})
	})

	h.Spin()
}

func registerMiddleware(h *server.Hertz) {
	
	// log
	secretKey := os.Getenv("SESSION_SECRET")
    if secretKey == "" {
        hlog.Fatal("SESSION_SECRET environment variable is not set")
    }
	store, _ := redis.NewStore(10, "tcp", conf.GetConf().Redis.Address,"", []byte(os.Getenv("SESSION_SECRET")))
	h.Use(sessions.New("cloudwego-shop", store))
	
	logger := hertzobslogrus.NewLogger(hertzobslogrus.WithLogger(hertzlogrus.NewLogger().Logger()))
	
	hlog.SetLogger(logger)
	hlog.SetLevel(conf.LogLevel())
	var flushInterval time.Duration
	if os.Getenv("GO_ENV")=="online"{
        flushInterval = time.Minute
	}else {
		flushInterval = time.Second
	}
	asyncWriter := &zapcore.BufferedWriteSyncer{
		WS: zapcore.AddSync(&lumberjack.Logger{
			Filename:   conf.GetConf().Hertz.LogFileName,
			MaxSize:    conf.GetConf().Hertz.LogMaxSize,
			MaxBackups: conf.GetConf().Hertz.LogMaxBackups,
			MaxAge:     conf.GetConf().Hertz.LogMaxAge,
		}),
		FlushInterval: flushInterval,
	}
	hlog.SetOutput(asyncWriter)
	h.OnShutdown = append(h.OnShutdown, func(ctx context.Context) {
		asyncWriter.Sync()
	})

	// pprof
	if conf.GetConf().Hertz.EnablePprof {
		pprof.Register(h)
	}

	// gzip
	if conf.GetConf().Hertz.EnableGzip {
		h.Use(gzip.Gzip(gzip.DefaultCompression))
	}

	// access log
	if conf.GetConf().Hertz.EnableAccessLog {
		h.Use(accesslog.New())
	}

	// recovery
	h.Use(recovery.Recovery())

	// cores
	h.Use(cors.Default())
	
	middleware.Register(h)
}
